version: 2
builds:
- id: tz
  binary: tz
  main: ./cmd/tz
  ldflags:
  - >
    -s -w
    -X "main.commit={{.Commit}}"
    -X "main.date={{.Date}}"
    -X "main.projectName={{.ProjectName}}"
    -X "main.version=v{{.Version}}"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64

checksum:
  name_template: checksums.txt

sboms:
- artifacts: archive

changelog:
  use: github-native
